_wandb:
    value:
        cli_version: 0.26.1
        e:
            fjqbsxw60ivxhlhkm5mn3xpky67tb8nb:
                codePath: test.py
                codePathLocal: test.py
                email: gyu6172@gmail.com
                executable: D:\anaconda_envs\kaggle\python.exe
                host: GyulaxyBook5Pro
                os: Windows-11-10.0.26200-SP0
                program: d:\Dev_Projects\디지털 경진대회 2026\contest_prac\test.py
                python: CPython 3.14.4
                root: D:\Dev_Projects\디지털 경진대회 2026\contest_prac
                startedAt: "2026-04-25T10:57:06.381595Z"
                writerId: fjqbsxw60ivxhlhkm5mn3xpky67tb8nb
        m: []
        python_version: 3.14.4
        t:
            "3":
                - 2
                - 13
            "4": 3.14.4
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 0.01
